//! Generated test file for BigInt.
//! DO NOT EDIT - This file is automatically generated.

use ziskos::syscalls::*;

pub fn test_bigint() {
    //////////////
    // Add256 Tests
    //////////////

    let a: [u64; 4] = [0, 0, 0, 0];
    let b: [u64; 4] = [0, 0, 0, 0];
    let mut c: [u64; 4] = [0, 0, 0, 0];
    let mut params = SyscallAdd256Params { a: &a, b: &b, cin: 0, c: &mut c };

    // Test #0: add256
    params.a = &[0, 0, 0, 0];
    params.b = &[0, 0, 0, 0];
    params.cin = 0;
    let cout = syscall_add256(&mut params);
    let expected_c: [u64; 4] = [0, 0, 0, 0];
    let expected_cout: u64 = 0;
    assert_eq!(params.c, &expected_c);
    assert_eq!(cout, expected_cout);

    // Test #1: add256
    params.a = &[11, 9, 7, 5];
    params.b = &[12, 10, 8, 6];
    params.cin = 0;
    let cout = syscall_add256(&mut params);
    let expected_c: [u64; 4] = [23, 19, 15, 11];
    let expected_cout: u64 = 0;
    assert_eq!(params.c, &expected_c);
    assert_eq!(cout, expected_cout);
}
