//! Generated test file for Sha256f.
//! DO NOT EDIT - This file is automatically generated.

use ziskos::syscalls::*;

pub fn test_sha256f() {
    //////////////
    // Sha256f Tests
    //////////////

    let mut state: [u64; 4] = [0, 0, 0, 0];
    let input: [u64; 8] = [0, 0, 0, 0, 0, 0, 0, 0];
    let mut params = SyscallSha256Params { state: &mut state, input: &input };

    // Test #0: sha256f
    let mut state: [u64; 4] =
        [7640891576010911365, 4354685563439150394, 5840696474761259148, 2270897967128956185];
    let input: [u64; 8] = [9223372036854775808, 0, 0, 0, 0, 0, 0, 0];
    params.state = &mut state;
    params.input = &input;
    syscall_sha256_f(&mut params);
    let expected_out: [u64; 4] =
        [16406829232824261652, 11167788843400149284, 2859295262623109964, 11859553537011923029];
    assert_eq!(params.state, &expected_out);
}
