//! Generated main test file.
//! DO NOT EDIT - This file is automatically generated.

#![no_main]
#![cfg(all(target_os = "zkvm", target_vendor = "zisk"))]
ziskos::entrypoint!(main);

mod arith_eq_tests;
mod arith_eq_384_tests;

fn main() {
	arith_eq_tests::test_arith_eq();
	arith_eq_384_tests::test_arith_eq_384();
}
