[package]
name = "keccak"
version = { workspace = true }
edition = { workspace = true }

[dependencies]
rand = { workspace = true }
byteorder = { workspace = true }
tiny-keccak = { workspace = true }
ziskos = { workspace = true }