

.PHONY : TARGET0
TARGET0 :
	@cd /workspace/output/riscof_work/rv64i_m/A/src/amoadd.d-01.S/dut; riscv64-unknown-elf-gcc -march=rv64ia          -static -mcmodel=medany -fvisibility=hidden -nostdlib -nostartfiles -g         -T /workspace/zisk/env/link.ld         -I /workspace/zisk/env/         -I /workspace/riscv-arch-test/riscv-test-suite/env /workspace/riscv-arch-test/riscv-test-suite/rv64i_m/A/src/amoadd.d-01.S -o my.elf  -DTEST_CASE_1=True -DXLEN=64 -Xlinker -Map=output.map -mabi=lp64 ; /program -e my.elf >/workspace/output/riscof_work/rv64i_m/A/src/amoadd.d-01.S/dut/DUT-zisk.signature;

.PHONY : TARGET1
TARGET1 :
	@cd /workspace/output/riscof_work/rv64i_m/A/src/amoadd.w-01.S/dut; riscv64-unknown-elf-gcc -march=rv64ia          -static -mcmodel=medany -fvisibility=hidden -nostdlib -nostartfiles -g         -T /workspace/zisk/env/link.ld         -I /workspace/zisk/env/         -I /workspace/riscv-arch-test/riscv-test-suite/env /workspace/riscv-arch-test/riscv-test-suite/rv64i_m/A/src/amoadd.w-01.S -o my.elf  -DTEST_CASE_1=True -DXLEN=64 -Xlinker -Map=output.map -mabi=lp64 ; /program -e my.elf >/workspace/output/riscof_work/rv64i_m/A/src/amoadd.w-01.S/dut/DUT-zisk.signature;

.PHONY : TARGET2
TARGET2 :
	@cd /workspace/output/riscof_work/rv64i_m/A/src/amoand.d-01.S/dut; riscv64-unknown-elf-gcc -march=rv64ia          -static -mcmodel=medany -fvisibility=hidden -nostdlib -nostartfiles -g         -T /workspace/zisk/env/link.ld         -I /workspace/zisk/env/         -I /workspace/riscv-arch-test/riscv-test-suite/env /workspace/riscv-arch-test/riscv-test-suite/rv64i_m/A/src/amoand.d-01.S -o my.elf  -DTEST_CASE_1=True -DXLEN=64 -Xlinker -Map=output.map -mabi=lp64 ; /program -e my.elf >/workspace/output/riscof_work/rv64i_m/A/src/amoand.d-01.S/dut/DUT-zisk.signature;

.PHONY : TARGET3
TARGET3 :
	@cd /workspace/output/riscof_work/rv64i_m/A/src/amoand.w-01.S/dut; riscv64-unknown-elf-gcc -march=rv64ia          -static -mcmodel=medany -fvisibility=hidden -nostdlib -nostartfiles -g         -T /workspace/zisk/env/link.ld         -I /workspace/zisk/env/         -I /workspace/riscv-arch-test/riscv-test-suite/env /workspace/riscv-arch-test/riscv-test-suite/rv64i_m/A/src/amoand.w-01.S -o my.elf  -DTEST_CASE_1=True -DXLEN=64 -Xlinker -Map=output.map -mabi=lp64 ; /program -e my.elf >/workspace/output/riscof_work/rv64i_m/A/src/amoand.w-01.S/dut/DUT-zisk.signature;

.PHONY : TARGET4
TARGET4 :
	@cd /workspace/output/riscof_work/rv64i_m/A/src/amomax.d-01.S/dut; riscv64-unknown-elf-gcc -march=rv64ia          -static -mcmodel=medany -fvisibility=hidden -nostdlib -nostartfiles -g         -T /workspace/zisk/env/link.ld         -I /workspace/zisk/env/         -I /workspace/riscv-arch-test/riscv-test-suite/env /workspace/riscv-arch-test/riscv-test-suite/rv64i_m/A/src/amomax.d-01.S -o my.elf  -DTEST_CASE_1=True -DXLEN=64 -Xlinker -Map=output.map -mabi=lp64 ; /program -e my.elf >/workspace/output/riscof_work/rv64i_m/A/src/amomax.d-01.S/dut/DUT-zisk.signature;

.PHONY : TARGET5
TARGET5 :
	@cd /workspace/output/riscof_work/rv64i_m/A/src/amomax.w-01.S/dut; riscv64-unknown-elf-gcc -march=rv64ia          -static -mcmodel=medany -fvisibility=hidden -nostdlib -nostartfiles -g         -T /workspace/zisk/env/link.ld         -I /workspace/zisk/env/         -I /workspace/riscv-arch-test/riscv-test-suite/env /workspace/riscv-arch-test/riscv-test-suite/rv64i_m/A/src/amomax.w-01.S -o my.elf  -DTEST_CASE_1=True -DXLEN=64 -Xlinker -Map=output.map -mabi=lp64 ; /program -e my.elf >/workspace/output/riscof_work/rv64i_m/A/src/amomax.w-01.S/dut/DUT-zisk.signature;

.PHONY : TARGET6
TARGET6 :
	@cd /workspace/output/riscof_work/rv64i_m/A/src/amomaxu.d-01.S/dut; riscv64-unknown-elf-gcc -march=rv64ia          -static -mcmodel=medany -fvisibility=hidden -nostdlib -nostartfiles -g         -T /workspace/zisk/env/link.ld         -I /workspace/zisk/env/         -I /workspace/riscv-arch-test/riscv-test-suite/env /workspace/riscv-arch-test/riscv-test-suite/rv64i_m/A/src/amomaxu.d-01.S -o my.elf  -DTEST_CASE_1=True -DXLEN=64 -Xlinker -Map=output.map -mabi=lp64 ; /program -e my.elf >/workspace/output/riscof_work/rv64i_m/A/src/amomaxu.d-01.S/dut/DUT-zisk.signature;

.PHONY : TARGET7
TARGET7 :
	@cd /workspace/output/riscof_work/rv64i_m/A/src/amomaxu.w-01.S/dut; riscv64-unknown-elf-gcc -march=rv64ia          -static -mcmodel=medany -fvisibility=hidden -nostdlib -nostartfiles -g         -T /workspace/zisk/env/link.ld         -I /workspace/zisk/env/         -I /workspace/riscv-arch-test/riscv-test-suite/env /workspace/riscv-arch-test/riscv-test-suite/rv64i_m/A/src/amomaxu.w-01.S -o my.elf  -DTEST_CASE_1=True -DXLEN=64 -Xlinker -Map=output.map -mabi=lp64 ; /program -e my.elf >/workspace/output/riscof_work/rv64i_m/A/src/amomaxu.w-01.S/dut/DUT-zisk.signature;

.PHONY : TARGET8
TARGET8 :
	@cd /workspace/output/riscof_work/rv64i_m/A/src/amomin.d-01.S/dut; riscv64-unknown-elf-gcc -march=rv64ia          -static -mcmodel=medany -fvisibility=hidden -nostdlib -nostartfiles -g         -T /workspace/zisk/env/link.ld         -I /workspace/zisk/env/         -I /workspace/riscv-arch-test/riscv-test-suite/env /workspace/riscv-arch-test/riscv-test-suite/rv64i_m/A/src/amomin.d-01.S -o my.elf  -DTEST_CASE_1=True -DXLEN=64 -Xlinker -Map=output.map -mabi=lp64 ; /program -e my.elf >/workspace/output/riscof_work/rv64i_m/A/src/amomin.d-01.S/dut/DUT-zisk.signature;

.PHONY : TARGET9
TARGET9 :
	@cd /workspace/output/riscof_work/rv64i_m/A/src/amomin.w-01.S/dut; riscv64-unknown-elf-gcc -march=rv64ia          -static -mcmodel=medany -fvisibility=hidden -nostdlib -nostartfiles -g         -T /workspace/zisk/env/link.ld         -I /workspace/zisk/env/         -I /workspace/riscv-arch-test/riscv-test-suite/env /workspace/riscv-arch-test/riscv-test-suite/rv64i_m/A/src/amomin.w-01.S -o my.elf  -DTEST_CASE_1=True -DXLEN=64 -Xlinker -Map=output.map -mabi=lp64 ; /program -e my.elf >/workspace/output/riscof_work/rv64i_m/A/src/amomin.w-01.S/dut/DUT-zisk.signature;

.PHONY : TARGET10
TARGET10 :
	@cd /workspace/output/riscof_work/rv64i_m/A/src/amominu.d-01.S/dut; riscv64-unknown-elf-gcc -march=rv64ia          -static -mcmodel=medany -fvisibility=hidden -nostdlib -nostartfiles -g         -T /workspace/zisk/env/link.ld         -I /workspace/zisk/env/         -I /workspace/riscv-arch-test/riscv-test-suite/env /workspace/riscv-arch-test/riscv-test-suite/rv64i_m/A/src/amominu.d-01.S -o my.elf  -DTEST_CASE_1=True -DXLEN=64 -Xlinker -Map=output.map -mabi=lp64 ; /program -e my.elf >/workspace/output/riscof_work/rv64i_m/A/src/amominu.d-01.S/dut/DUT-zisk.signature;

.PHONY : TARGET11
TARGET11 :
	@cd /workspace/output/riscof_work/rv64i_m/A/src/amominu.w-01.S/dut; riscv64-unknown-elf-gcc -march=rv64ia          -static -mcmodel=medany -fvisibility=hidden -nostdlib -nostartfiles -g         -T /workspace/zisk/env/link.ld         -I /workspace/zisk/env/         -I /workspace/riscv-arch-test/riscv-test-suite/env /workspace/riscv-arch-test/riscv-test-suite/rv64i_m/A/src/amominu.w-01.S -o my.elf  -DTEST_CASE_1=True -DXLEN=64 -Xlinker -Map=output.map -mabi=lp64 ; /program -e my.elf >/workspace/output/riscof_work/rv64i_m/A/src/amominu.w-01.S/dut/DUT-zisk.signature;

.PHONY : TARGET12
TARGET12 :
	@cd /workspace/output/riscof_work/rv64i_m/A/src/amoor.d-01.S/dut; riscv64-unknown-elf-gcc -march=rv64ia          -static -mcmodel=medany -fvisibility=hidden -nostdlib -nostartfiles -g         -T /workspace/zisk/env/link.ld         -I /workspace/zisk/env/         -I /workspace/riscv-arch-test/riscv-test-suite/env /workspace/riscv-arch-test/riscv-test-suite/rv64i_m/A/src/amoor.d-01.S -o my.elf  -DTEST_CASE_1=True -DXLEN=64 -Xlinker -Map=output.map -mabi=lp64 ; /program -e my.elf >/workspace/output/riscof_work/rv64i_m/A/src/amoor.d-01.S/dut/DUT-zisk.signature;

.PHONY : TARGET13
TARGET13 :
	@cd /workspace/output/riscof_work/rv64i_m/A/src/amoor.w-01.S/dut; riscv64-unknown-elf-gcc -march=rv64ia          -static -mcmodel=medany -fvisibility=hidden -nostdlib -nostartfiles -g         -T /workspace/zisk/env/link.ld         -I /workspace/zisk/env/         -I /workspace/riscv-arch-test/riscv-test-suite/env /workspace/riscv-arch-test/riscv-test-suite/rv64i_m/A/src/amoor.w-01.S -o my.elf  -DTEST_CASE_1=True -DXLEN=64 -Xlinker -Map=output.map -mabi=lp64 ; /program -e my.elf >/workspace/output/riscof_work/rv64i_m/A/src/amoor.w-01.S/dut/DUT-zisk.signature;

.PHONY : TARGET14
TARGET14 :
	@cd /workspace/output/riscof_work/rv64i_m/A/src/amoswap.d-01.S/dut; riscv64-unknown-elf-gcc -march=rv64ia          -static -mcmodel=medany -fvisibility=hidden -nostdlib -nostartfiles -g         -T /workspace/zisk/env/link.ld         -I /workspace/zisk/env/         -I /workspace/riscv-arch-test/riscv-test-suite/env /workspace/riscv-arch-test/riscv-test-suite/rv64i_m/A/src/amoswap.d-01.S -o my.elf  -DTEST_CASE_1=True -DXLEN=64 -Xlinker -Map=output.map -mabi=lp64 ; /program -e my.elf >/workspace/output/riscof_work/rv64i_m/A/src/amoswap.d-01.S/dut/DUT-zisk.signature;

.PHONY : TARGET15
TARGET15 :
	@cd /workspace/output/riscof_work/rv64i_m/A/src/amoswap.w-01.S/dut; riscv64-unknown-elf-gcc -march=rv64ia          -static -mcmodel=medany -fvisibility=hidden -nostdlib -nostartfiles -g         -T /workspace/zisk/env/link.ld         -I /workspace/zisk/env/         -I /workspace/riscv-arch-test/riscv-test-suite/env /workspace/riscv-arch-test/riscv-test-suite/rv64i_m/A/src/amoswap.w-01.S -o my.elf  -DTEST_CASE_1=True -DXLEN=64 -Xlinker -Map=output.map -mabi=lp64 ; /program -e my.elf >/workspace/output/riscof_work/rv64i_m/A/src/amoswap.w-01.S/dut/DUT-zisk.signature;

.PHONY : TARGET16
TARGET16 :
	@cd /workspace/output/riscof_work/rv64i_m/A/src/amoxor.d-01.S/dut; riscv64-unknown-elf-gcc -march=rv64ia          -static -mcmodel=medany -fvisibility=hidden -nostdlib -nostartfiles -g         -T /workspace/zisk/env/link.ld         -I /workspace/zisk/env/         -I /workspace/riscv-arch-test/riscv-test-suite/env /workspace/riscv-arch-test/riscv-test-suite/rv64i_m/A/src/amoxor.d-01.S -o my.elf  -DTEST_CASE_1=True -DXLEN=64 -Xlinker -Map=output.map -mabi=lp64 ; /program -e my.elf >/workspace/output/riscof_work/rv64i_m/A/src/amoxor.d-01.S/dut/DUT-zisk.signature;

.PHONY : TARGET17
TARGET17 :
	@cd /workspace/output/riscof_work/rv64i_m/A/src/amoxor.w-01.S/dut; riscv64-unknown-elf-gcc -march=rv64ia          -static -mcmodel=medany -fvisibility=hidden -nostdlib -nostartfiles -g         -T /workspace/zisk/env/link.ld         -I /workspace/zisk/env/         -I /workspace/riscv-arch-test/riscv-test-suite/env /workspace/riscv-arch-test/riscv-test-suite/rv64i_m/A/src/amoxor.w-01.S -o my.elf  -DTEST_CASE_1=True -DXLEN=64 -Xlinker -Map=output.map -mabi=lp64 ; /program -e my.elf >/workspace/output/riscof_work/rv64i_m/A/src/amoxor.w-01.S/dut/DUT-zisk.signature;

.PHONY : TARGET18
TARGET18 :
	@cd /workspace/output/riscof_work/rv64i_m/I/src/add-01.S/dut; riscv64-unknown-elf-gcc -march=rv64i          -static -mcmodel=medany -fvisibility=hidden -nostdlib -nostartfiles -g         -T /workspace/zisk/env/link.ld         -I /workspace/zisk/env/         -I /workspace/riscv-arch-test/riscv-test-suite/env /workspace/riscv-arch-test/riscv-test-suite/rv64i_m/I/src/add-01.S -o my.elf  -DTEST_CASE_1=True -DXLEN=64 -Xlinker -Map=output.map -mabi=lp64 ; /program -e my.elf >/workspace/output/riscof_work/rv64i_m/I/src/add-01.S/dut/DUT-zisk.signature;

.PHONY : TARGET19
TARGET19 :
	@cd /workspace/output/riscof_work/rv64i_m/I/src/addi-01.S/dut; riscv64-unknown-elf-gcc -march=rv64i          -static -mcmodel=medany -fvisibility=hidden -nostdlib -nostartfiles -g         -T /workspace/zisk/env/link.ld         -I /workspace/zisk/env/         -I /workspace/riscv-arch-test/riscv-test-suite/env /workspace/riscv-arch-test/riscv-test-suite/rv64i_m/I/src/addi-01.S -o my.elf  -DTEST_CASE_1=True -DXLEN=64 -Xlinker -Map=output.map -mabi=lp64 ; /program -e my.elf >/workspace/output/riscof_work/rv64i_m/I/src/addi-01.S/dut/DUT-zisk.signature;

.PHONY : TARGET20
TARGET20 :
	@cd /workspace/output/riscof_work/rv64i_m/I/src/addiw-01.S/dut; riscv64-unknown-elf-gcc -march=rv64i          -static -mcmodel=medany -fvisibility=hidden -nostdlib -nostartfiles -g         -T /workspace/zisk/env/link.ld         -I /workspace/zisk/env/         -I /workspace/riscv-arch-test/riscv-test-suite/env /workspace/riscv-arch-test/riscv-test-suite/rv64i_m/I/src/addiw-01.S -o my.elf  -DTEST_CASE_1=True -DXLEN=64 -Xlinker -Map=output.map -mabi=lp64 ; /program -e my.elf >/workspace/output/riscof_work/rv64i_m/I/src/addiw-01.S/dut/DUT-zisk.signature;

.PHONY : TARGET21
TARGET21 :
	@cd /workspace/output/riscof_work/rv64i_m/I/src/addw-01.S/dut; riscv64-unknown-elf-gcc -march=rv64i          -static -mcmodel=medany -fvisibility=hidden -nostdlib -nostartfiles -g         -T /workspace/zisk/env/link.ld         -I /workspace/zisk/env/         -I /workspace/riscv-arch-test/riscv-test-suite/env /workspace/riscv-arch-test/riscv-test-suite/rv64i_m/I/src/addw-01.S -o my.elf  -DTEST_CASE_1=True -DXLEN=64 -Xlinker -Map=output.map -mabi=lp64 ; /program -e my.elf >/workspace/output/riscof_work/rv64i_m/I/src/addw-01.S/dut/DUT-zisk.signature;

.PHONY : TARGET22
TARGET22 :
	@cd /workspace/output/riscof_work/rv64i_m/I/src/and-01.S/dut; riscv64-unknown-elf-gcc -march=rv64i          -static -mcmodel=medany -fvisibility=hidden -nostdlib -nostartfiles -g         -T /workspace/zisk/env/link.ld         -I /workspace/zisk/env/         -I /workspace/riscv-arch-test/riscv-test-suite/env /workspace/riscv-arch-test/riscv-test-suite/rv64i_m/I/src/and-01.S -o my.elf  -DTEST_CASE_1=True -DXLEN=64 -Xlinker -Map=output.map -mabi=lp64 ; /program -e my.elf >/workspace/output/riscof_work/rv64i_m/I/src/and-01.S/dut/DUT-zisk.signature;

.PHONY : TARGET23
TARGET23 :
	@cd /workspace/output/riscof_work/rv64i_m/I/src/andi-01.S/dut; riscv64-unknown-elf-gcc -march=rv64i          -static -mcmodel=medany -fvisibility=hidden -nostdlib -nostartfiles -g         -T /workspace/zisk/env/link.ld         -I /workspace/zisk/env/         -I /workspace/riscv-arch-test/riscv-test-suite/env /workspace/riscv-arch-test/riscv-test-suite/rv64i_m/I/src/andi-01.S -o my.elf  -DTEST_CASE_1=True -DXLEN=64 -Xlinker -Map=output.map -mabi=lp64 ; /program -e my.elf >/workspace/output/riscof_work/rv64i_m/I/src/andi-01.S/dut/DUT-zisk.signature;

.PHONY : TARGET24
TARGET24 :
	@cd /workspace/output/riscof_work/rv64i_m/I/src/auipc-01.S/dut; riscv64-unknown-elf-gcc -march=rv64i          -static -mcmodel=medany -fvisibility=hidden -nostdlib -nostartfiles -g         -T /workspace/zisk/env/link.ld         -I /workspace/zisk/env/         -I /workspace/riscv-arch-test/riscv-test-suite/env /workspace/riscv-arch-test/riscv-test-suite/rv64i_m/I/src/auipc-01.S -o my.elf  -DTEST_CASE_1=True -DXLEN=64 -Xlinker -Map=output.map -mabi=lp64 ; /program -e my.elf >/workspace/output/riscof_work/rv64i_m/I/src/auipc-01.S/dut/DUT-zisk.signature;

.PHONY : TARGET25
TARGET25 :
	@cd /workspace/output/riscof_work/rv64i_m/I/src/beq-01.S/dut; riscv64-unknown-elf-gcc -march=rv64i          -static -mcmodel=medany -fvisibility=hidden -nostdlib -nostartfiles -g         -T /workspace/zisk/env/link.ld         -I /workspace/zisk/env/         -I /workspace/riscv-arch-test/riscv-test-suite/env /workspace/riscv-arch-test/riscv-test-suite/rv64i_m/I/src/beq-01.S -o my.elf  -DTEST_CASE_1=True -DXLEN=64 -Xlinker -Map=output.map -mabi=lp64 ; /program -e my.elf >/workspace/output/riscof_work/rv64i_m/I/src/beq-01.S/dut/DUT-zisk.signature;

.PHONY : TARGET26
TARGET26 :
	@cd /workspace/output/riscof_work/rv64i_m/I/src/bge-01.S/dut; riscv64-unknown-elf-gcc -march=rv64i          -static -mcmodel=medany -fvisibility=hidden -nostdlib -nostartfiles -g         -T /workspace/zisk/env/link.ld         -I /workspace/zisk/env/         -I /workspace/riscv-arch-test/riscv-test-suite/env /workspace/riscv-arch-test/riscv-test-suite/rv64i_m/I/src/bge-01.S -o my.elf  -DTEST_CASE_1=True -DXLEN=64 -Xlinker -Map=output.map -mabi=lp64 ; /program -e my.elf >/workspace/output/riscof_work/rv64i_m/I/src/bge-01.S/dut/DUT-zisk.signature;

.PHONY : TARGET27
TARGET27 :
	@cd /workspace/output/riscof_work/rv64i_m/I/src/bgeu-01.S/dut; riscv64-unknown-elf-gcc -march=rv64i          -static -mcmodel=medany -fvisibility=hidden -nostdlib -nostartfiles -g         -T /workspace/zisk/env/link.ld         -I /workspace/zisk/env/         -I /workspace/riscv-arch-test/riscv-test-suite/env /workspace/riscv-arch-test/riscv-test-suite/rv64i_m/I/src/bgeu-01.S -o my.elf  -DTEST_CASE_1=True -DXLEN=64 -Xlinker -Map=output.map -mabi=lp64 ; /program -e my.elf >/workspace/output/riscof_work/rv64i_m/I/src/bgeu-01.S/dut/DUT-zisk.signature;

.PHONY : TARGET28
TARGET28 :
	@cd /workspace/output/riscof_work/rv64i_m/I/src/blt-01.S/dut; riscv64-unknown-elf-gcc -march=rv64i          -static -mcmodel=medany -fvisibility=hidden -nostdlib -nostartfiles -g         -T /workspace/zisk/env/link.ld         -I /workspace/zisk/env/         -I /workspace/riscv-arch-test/riscv-test-suite/env /workspace/riscv-arch-test/riscv-test-suite/rv64i_m/I/src/blt-01.S -o my.elf  -DTEST_CASE_1=True -DXLEN=64 -Xlinker -Map=output.map -mabi=lp64 ; /program -e my.elf >/workspace/output/riscof_work/rv64i_m/I/src/blt-01.S/dut/DUT-zisk.signature;

.PHONY : TARGET29
TARGET29 :
	@cd /workspace/output/riscof_work/rv64i_m/I/src/bltu-01.S/dut; riscv64-unknown-elf-gcc -march=rv64i          -static -mcmodel=medany -fvisibility=hidden -nostdlib -nostartfiles -g         -T /workspace/zisk/env/link.ld         -I /workspace/zisk/env/         -I /workspace/riscv-arch-test/riscv-test-suite/env /workspace/riscv-arch-test/riscv-test-suite/rv64i_m/I/src/bltu-01.S -o my.elf  -DTEST_CASE_1=True -DXLEN=64 -Xlinker -Map=output.map -mabi=lp64 ; /program -e my.elf >/workspace/output/riscof_work/rv64i_m/I/src/bltu-01.S/dut/DUT-zisk.signature;

.PHONY : TARGET30
TARGET30 :
	@cd /workspace/output/riscof_work/rv64i_m/I/src/bne-01.S/dut; riscv64-unknown-elf-gcc -march=rv64i          -static -mcmodel=medany -fvisibility=hidden -nostdlib -nostartfiles -g         -T /workspace/zisk/env/link.ld         -I /workspace/zisk/env/         -I /workspace/riscv-arch-test/riscv-test-suite/env /workspace/riscv-arch-test/riscv-test-suite/rv64i_m/I/src/bne-01.S -o my.elf  -DTEST_CASE_1=True -DXLEN=64 -Xlinker -Map=output.map -mabi=lp64 ; /program -e my.elf >/workspace/output/riscof_work/rv64i_m/I/src/bne-01.S/dut/DUT-zisk.signature;

.PHONY : TARGET31
TARGET31 :
	@cd /workspace/output/riscof_work/rv64i_m/I/src/fence-01.S/dut; riscv64-unknown-elf-gcc -march=rv64i          -static -mcmodel=medany -fvisibility=hidden -nostdlib -nostartfiles -g         -T /workspace/zisk/env/link.ld         -I /workspace/zisk/env/         -I /workspace/riscv-arch-test/riscv-test-suite/env /workspace/riscv-arch-test/riscv-test-suite/rv64i_m/I/src/fence-01.S -o my.elf  -DTEST_CASE_1=True -DXLEN=64 -Xlinker -Map=output.map -mabi=lp64 ; /program -e my.elf >/workspace/output/riscof_work/rv64i_m/I/src/fence-01.S/dut/DUT-zisk.signature;

.PHONY : TARGET32
TARGET32 :
	@cd /workspace/output/riscof_work/rv64i_m/I/src/jal-01.S/dut; riscv64-unknown-elf-gcc -march=rv64i          -static -mcmodel=medany -fvisibility=hidden -nostdlib -nostartfiles -g         -T /workspace/zisk/env/link.ld         -I /workspace/zisk/env/         -I /workspace/riscv-arch-test/riscv-test-suite/env /workspace/riscv-arch-test/riscv-test-suite/rv64i_m/I/src/jal-01.S -o my.elf  -DTEST_CASE_1=True -DXLEN=64 -Xlinker -Map=output.map -mabi=lp64 ; /program -e my.elf >/workspace/output/riscof_work/rv64i_m/I/src/jal-01.S/dut/DUT-zisk.signature;

.PHONY : TARGET33
TARGET33 :
	@cd /workspace/output/riscof_work/rv64i_m/I/src/jalr-01.S/dut; riscv64-unknown-elf-gcc -march=rv64i          -static -mcmodel=medany -fvisibility=hidden -nostdlib -nostartfiles -g         -T /workspace/zisk/env/link.ld         -I /workspace/zisk/env/         -I /workspace/riscv-arch-test/riscv-test-suite/env /workspace/riscv-arch-test/riscv-test-suite/rv64i_m/I/src/jalr-01.S -o my.elf  -DTEST_CASE_1=True -DXLEN=64 -Xlinker -Map=output.map -mabi=lp64 ; /program -e my.elf >/workspace/output/riscof_work/rv64i_m/I/src/jalr-01.S/dut/DUT-zisk.signature;

.PHONY : TARGET34
TARGET34 :
	@cd /workspace/output/riscof_work/rv64i_m/I/src/lb-align-01.S/dut; riscv64-unknown-elf-gcc -march=rv64i          -static -mcmodel=medany -fvisibility=hidden -nostdlib -nostartfiles -g         -T /workspace/zisk/env/link.ld         -I /workspace/zisk/env/         -I /workspace/riscv-arch-test/riscv-test-suite/env /workspace/riscv-arch-test/riscv-test-suite/rv64i_m/I/src/lb-align-01.S -o my.elf  -DTEST_CASE_1=True -DXLEN=64 -Xlinker -Map=output.map -mabi=lp64 ; /program -e my.elf >/workspace/output/riscof_work/rv64i_m/I/src/lb-align-01.S/dut/DUT-zisk.signature;

.PHONY : TARGET35
TARGET35 :
	@cd /workspace/output/riscof_work/rv64i_m/I/src/lbu-align-01.S/dut; riscv64-unknown-elf-gcc -march=rv64i          -static -mcmodel=medany -fvisibility=hidden -nostdlib -nostartfiles -g         -T /workspace/zisk/env/link.ld         -I /workspace/zisk/env/         -I /workspace/riscv-arch-test/riscv-test-suite/env /workspace/riscv-arch-test/riscv-test-suite/rv64i_m/I/src/lbu-align-01.S -o my.elf  -DTEST_CASE_1=True -DXLEN=64 -Xlinker -Map=output.map -mabi=lp64 ; /program -e my.elf >/workspace/output/riscof_work/rv64i_m/I/src/lbu-align-01.S/dut/DUT-zisk.signature;

.PHONY : TARGET36
TARGET36 :
	@cd /workspace/output/riscof_work/rv64i_m/I/src/ld-align-01.S/dut; riscv64-unknown-elf-gcc -march=rv64i          -static -mcmodel=medany -fvisibility=hidden -nostdlib -nostartfiles -g         -T /workspace/zisk/env/link.ld         -I /workspace/zisk/env/         -I /workspace/riscv-arch-test/riscv-test-suite/env /workspace/riscv-arch-test/riscv-test-suite/rv64i_m/I/src/ld-align-01.S -o my.elf  -DTEST_CASE_1=True -DXLEN=64 -Xlinker -Map=output.map -mabi=lp64 ; /program -e my.elf >/workspace/output/riscof_work/rv64i_m/I/src/ld-align-01.S/dut/DUT-zisk.signature;

.PHONY : TARGET37
TARGET37 :
	@cd /workspace/output/riscof_work/rv64i_m/I/src/lh-align-01.S/dut; riscv64-unknown-elf-gcc -march=rv64i          -static -mcmodel=medany -fvisibility=hidden -nostdlib -nostartfiles -g         -T /workspace/zisk/env/link.ld         -I /workspace/zisk/env/         -I /workspace/riscv-arch-test/riscv-test-suite/env /workspace/riscv-arch-test/riscv-test-suite/rv64i_m/I/src/lh-align-01.S -o my.elf  -DTEST_CASE_1=True -DXLEN=64 -Xlinker -Map=output.map -mabi=lp64 ; /program -e my.elf >/workspace/output/riscof_work/rv64i_m/I/src/lh-align-01.S/dut/DUT-zisk.signature;

.PHONY : TARGET38
TARGET38 :
	@cd /workspace/output/riscof_work/rv64i_m/I/src/lhu-align-01.S/dut; riscv64-unknown-elf-gcc -march=rv64i          -static -mcmodel=medany -fvisibility=hidden -nostdlib -nostartfiles -g         -T /workspace/zisk/env/link.ld         -I /workspace/zisk/env/         -I /workspace/riscv-arch-test/riscv-test-suite/env /workspace/riscv-arch-test/riscv-test-suite/rv64i_m/I/src/lhu-align-01.S -o my.elf  -DTEST_CASE_1=True -DXLEN=64 -Xlinker -Map=output.map -mabi=lp64 ; /program -e my.elf >/workspace/output/riscof_work/rv64i_m/I/src/lhu-align-01.S/dut/DUT-zisk.signature;

.PHONY : TARGET39
TARGET39 :
	@cd /workspace/output/riscof_work/rv64i_m/I/src/lui-01.S/dut; riscv64-unknown-elf-gcc -march=rv64i          -static -mcmodel=medany -fvisibility=hidden -nostdlib -nostartfiles -g         -T /workspace/zisk/env/link.ld         -I /workspace/zisk/env/         -I /workspace/riscv-arch-test/riscv-test-suite/env /workspace/riscv-arch-test/riscv-test-suite/rv64i_m/I/src/lui-01.S -o my.elf  -DTEST_CASE_1=True -DXLEN=64 -Xlinker -Map=output.map -mabi=lp64 ; /program -e my.elf >/workspace/output/riscof_work/rv64i_m/I/src/lui-01.S/dut/DUT-zisk.signature;

.PHONY : TARGET40
TARGET40 :
	@cd /workspace/output/riscof_work/rv64i_m/I/src/lw-align-01.S/dut; riscv64-unknown-elf-gcc -march=rv64i          -static -mcmodel=medany -fvisibility=hidden -nostdlib -nostartfiles -g         -T /workspace/zisk/env/link.ld         -I /workspace/zisk/env/         -I /workspace/riscv-arch-test/riscv-test-suite/env /workspace/riscv-arch-test/riscv-test-suite/rv64i_m/I/src/lw-align-01.S -o my.elf  -DTEST_CASE_1=True -DXLEN=64 -Xlinker -Map=output.map -mabi=lp64 ; /program -e my.elf >/workspace/output/riscof_work/rv64i_m/I/src/lw-align-01.S/dut/DUT-zisk.signature;

.PHONY : TARGET41
TARGET41 :
	@cd /workspace/output/riscof_work/rv64i_m/I/src/lwu-align-01.S/dut; riscv64-unknown-elf-gcc -march=rv64i          -static -mcmodel=medany -fvisibility=hidden -nostdlib -nostartfiles -g         -T /workspace/zisk/env/link.ld         -I /workspace/zisk/env/         -I /workspace/riscv-arch-test/riscv-test-suite/env /workspace/riscv-arch-test/riscv-test-suite/rv64i_m/I/src/lwu-align-01.S -o my.elf  -DTEST_CASE_1=True -DXLEN=64 -Xlinker -Map=output.map -mabi=lp64 ; /program -e my.elf >/workspace/output/riscof_work/rv64i_m/I/src/lwu-align-01.S/dut/DUT-zisk.signature;

.PHONY : TARGET42
TARGET42 :
	@cd /workspace/output/riscof_work/rv64i_m/I/src/misalign1-jalr-01.S/dut; riscv64-unknown-elf-gcc -march=rv64i          -static -mcmodel=medany -fvisibility=hidden -nostdlib -nostartfiles -g         -T /workspace/zisk/env/link.ld         -I /workspace/zisk/env/         -I /workspace/riscv-arch-test/riscv-test-suite/env /workspace/riscv-arch-test/riscv-test-suite/rv64i_m/I/src/misalign1-jalr-01.S -o my.elf  -DTEST_CASE_1=True -DXLEN=64 -Xlinker -Map=output.map -mabi=lp64 ; /program -e my.elf >/workspace/output/riscof_work/rv64i_m/I/src/misalign1-jalr-01.S/dut/DUT-zisk.signature;

.PHONY : TARGET43
TARGET43 :
	@cd /workspace/output/riscof_work/rv64i_m/I/src/or-01.S/dut; riscv64-unknown-elf-gcc -march=rv64i          -static -mcmodel=medany -fvisibility=hidden -nostdlib -nostartfiles -g         -T /workspace/zisk/env/link.ld         -I /workspace/zisk/env/         -I /workspace/riscv-arch-test/riscv-test-suite/env /workspace/riscv-arch-test/riscv-test-suite/rv64i_m/I/src/or-01.S -o my.elf  -DTEST_CASE_1=True -DXLEN=64 -Xlinker -Map=output.map -mabi=lp64 ; /program -e my.elf >/workspace/output/riscof_work/rv64i_m/I/src/or-01.S/dut/DUT-zisk.signature;

.PHONY : TARGET44
TARGET44 :
	@cd /workspace/output/riscof_work/rv64i_m/I/src/ori-01.S/dut; riscv64-unknown-elf-gcc -march=rv64i          -static -mcmodel=medany -fvisibility=hidden -nostdlib -nostartfiles -g         -T /workspace/zisk/env/link.ld         -I /workspace/zisk/env/         -I /workspace/riscv-arch-test/riscv-test-suite/env /workspace/riscv-arch-test/riscv-test-suite/rv64i_m/I/src/ori-01.S -o my.elf  -DTEST_CASE_1=True -DXLEN=64 -Xlinker -Map=output.map -mabi=lp64 ; /program -e my.elf >/workspace/output/riscof_work/rv64i_m/I/src/ori-01.S/dut/DUT-zisk.signature;

.PHONY : TARGET45
TARGET45 :
	@cd /workspace/output/riscof_work/rv64i_m/I/src/sb-align-01.S/dut; riscv64-unknown-elf-gcc -march=rv64i          -static -mcmodel=medany -fvisibility=hidden -nostdlib -nostartfiles -g         -T /workspace/zisk/env/link.ld         -I /workspace/zisk/env/         -I /workspace/riscv-arch-test/riscv-test-suite/env /workspace/riscv-arch-test/riscv-test-suite/rv64i_m/I/src/sb-align-01.S -o my.elf  -DTEST_CASE_1=True -DXLEN=64 -Xlinker -Map=output.map -mabi=lp64 ; /program -e my.elf >/workspace/output/riscof_work/rv64i_m/I/src/sb-align-01.S/dut/DUT-zisk.signature;

.PHONY : TARGET46
TARGET46 :
	@cd /workspace/output/riscof_work/rv64i_m/I/src/sd-align-01.S/dut; riscv64-unknown-elf-gcc -march=rv64i          -static -mcmodel=medany -fvisibility=hidden -nostdlib -nostartfiles -g         -T /workspace/zisk/env/link.ld         -I /workspace/zisk/env/         -I /workspace/riscv-arch-test/riscv-test-suite/env /workspace/riscv-arch-test/riscv-test-suite/rv64i_m/I/src/sd-align-01.S -o my.elf  -DTEST_CASE_1=True -DXLEN=64 -Xlinker -Map=output.map -mabi=lp64 ; /program -e my.elf >/workspace/output/riscof_work/rv64i_m/I/src/sd-align-01.S/dut/DUT-zisk.signature;

.PHONY : TARGET47
TARGET47 :
	@cd /workspace/output/riscof_work/rv64i_m/I/src/sh-align-01.S/dut; riscv64-unknown-elf-gcc -march=rv64i          -static -mcmodel=medany -fvisibility=hidden -nostdlib -nostartfiles -g         -T /workspace/zisk/env/link.ld         -I /workspace/zisk/env/         -I /workspace/riscv-arch-test/riscv-test-suite/env /workspace/riscv-arch-test/riscv-test-suite/rv64i_m/I/src/sh-align-01.S -o my.elf  -DTEST_CASE_1=True -DXLEN=64 -Xlinker -Map=output.map -mabi=lp64 ; /program -e my.elf >/workspace/output/riscof_work/rv64i_m/I/src/sh-align-01.S/dut/DUT-zisk.signature;

.PHONY : TARGET48
TARGET48 :
	@cd /workspace/output/riscof_work/rv64i_m/I/src/sll-01.S/dut; riscv64-unknown-elf-gcc -march=rv64i          -static -mcmodel=medany -fvisibility=hidden -nostdlib -nostartfiles -g         -T /workspace/zisk/env/link.ld         -I /workspace/zisk/env/         -I /workspace/riscv-arch-test/riscv-test-suite/env /workspace/riscv-arch-test/riscv-test-suite/rv64i_m/I/src/sll-01.S -o my.elf  -DTEST_CASE_1=True -DXLEN=64 -Xlinker -Map=output.map -mabi=lp64 ; /program -e my.elf >/workspace/output/riscof_work/rv64i_m/I/src/sll-01.S/dut/DUT-zisk.signature;

.PHONY : TARGET49
TARGET49 :
	@cd /workspace/output/riscof_work/rv64i_m/I/src/slli-01.S/dut; riscv64-unknown-elf-gcc -march=rv64i          -static -mcmodel=medany -fvisibility=hidden -nostdlib -nostartfiles -g         -T /workspace/zisk/env/link.ld         -I /workspace/zisk/env/         -I /workspace/riscv-arch-test/riscv-test-suite/env /workspace/riscv-arch-test/riscv-test-suite/rv64i_m/I/src/slli-01.S -o my.elf  -DTEST_CASE_1=True -DXLEN=64 -Xlinker -Map=output.map -mabi=lp64 ; /program -e my.elf >/workspace/output/riscof_work/rv64i_m/I/src/slli-01.S/dut/DUT-zisk.signature;

.PHONY : TARGET50
TARGET50 :
	@cd /workspace/output/riscof_work/rv64i_m/I/src/slliw-01.S/dut; riscv64-unknown-elf-gcc -march=rv64i          -static -mcmodel=medany -fvisibility=hidden -nostdlib -nostartfiles -g         -T /workspace/zisk/env/link.ld         -I /workspace/zisk/env/         -I /workspace/riscv-arch-test/riscv-test-suite/env /workspace/riscv-arch-test/riscv-test-suite/rv64i_m/I/src/slliw-01.S -o my.elf  -DTEST_CASE_1=True -DXLEN=64 -Xlinker -Map=output.map -mabi=lp64 ; /program -e my.elf >/workspace/output/riscof_work/rv64i_m/I/src/slliw-01.S/dut/DUT-zisk.signature;

.PHONY : TARGET51
TARGET51 :
	@cd /workspace/output/riscof_work/rv64i_m/I/src/sllw-01.S/dut; riscv64-unknown-elf-gcc -march=rv64i          -static -mcmodel=medany -fvisibility=hidden -nostdlib -nostartfiles -g         -T /workspace/zisk/env/link.ld         -I /workspace/zisk/env/         -I /workspace/riscv-arch-test/riscv-test-suite/env /workspace/riscv-arch-test/riscv-test-suite/rv64i_m/I/src/sllw-01.S -o my.elf  -DTEST_CASE_1=True -DXLEN=64 -Xlinker -Map=output.map -mabi=lp64 ; /program -e my.elf >/workspace/output/riscof_work/rv64i_m/I/src/sllw-01.S/dut/DUT-zisk.signature;

.PHONY : TARGET52
TARGET52 :
	@cd /workspace/output/riscof_work/rv64i_m/I/src/slt-01.S/dut; riscv64-unknown-elf-gcc -march=rv64i          -static -mcmodel=medany -fvisibility=hidden -nostdlib -nostartfiles -g         -T /workspace/zisk/env/link.ld         -I /workspace/zisk/env/         -I /workspace/riscv-arch-test/riscv-test-suite/env /workspace/riscv-arch-test/riscv-test-suite/rv64i_m/I/src/slt-01.S -o my.elf  -DTEST_CASE_1=True -DXLEN=64 -Xlinker -Map=output.map -mabi=lp64 ; /program -e my.elf >/workspace/output/riscof_work/rv64i_m/I/src/slt-01.S/dut/DUT-zisk.signature;

.PHONY : TARGET53
TARGET53 :
	@cd /workspace/output/riscof_work/rv64i_m/I/src/slti-01.S/dut; riscv64-unknown-elf-gcc -march=rv64i          -static -mcmodel=medany -fvisibility=hidden -nostdlib -nostartfiles -g         -T /workspace/zisk/env/link.ld         -I /workspace/zisk/env/         -I /workspace/riscv-arch-test/riscv-test-suite/env /workspace/riscv-arch-test/riscv-test-suite/rv64i_m/I/src/slti-01.S -o my.elf  -DTEST_CASE_1=True -DXLEN=64 -Xlinker -Map=output.map -mabi=lp64 ; /program -e my.elf >/workspace/output/riscof_work/rv64i_m/I/src/slti-01.S/dut/DUT-zisk.signature;

.PHONY : TARGET54
TARGET54 :
	@cd /workspace/output/riscof_work/rv64i_m/I/src/sltiu-01.S/dut; riscv64-unknown-elf-gcc -march=rv64i          -static -mcmodel=medany -fvisibility=hidden -nostdlib -nostartfiles -g         -T /workspace/zisk/env/link.ld         -I /workspace/zisk/env/         -I /workspace/riscv-arch-test/riscv-test-suite/env /workspace/riscv-arch-test/riscv-test-suite/rv64i_m/I/src/sltiu-01.S -o my.elf  -DTEST_CASE_1=True -DXLEN=64 -Xlinker -Map=output.map -mabi=lp64 ; /program -e my.elf >/workspace/output/riscof_work/rv64i_m/I/src/sltiu-01.S/dut/DUT-zisk.signature;

.PHONY : TARGET55
TARGET55 :
	@cd /workspace/output/riscof_work/rv64i_m/I/src/sltu-01.S/dut; riscv64-unknown-elf-gcc -march=rv64i          -static -mcmodel=medany -fvisibility=hidden -nostdlib -nostartfiles -g         -T /workspace/zisk/env/link.ld         -I /workspace/zisk/env/         -I /workspace/riscv-arch-test/riscv-test-suite/env /workspace/riscv-arch-test/riscv-test-suite/rv64i_m/I/src/sltu-01.S -o my.elf  -DTEST_CASE_1=True -DXLEN=64 -Xlinker -Map=output.map -mabi=lp64 ; /program -e my.elf >/workspace/output/riscof_work/rv64i_m/I/src/sltu-01.S/dut/DUT-zisk.signature;

.PHONY : TARGET56
TARGET56 :
	@cd /workspace/output/riscof_work/rv64i_m/I/src/sra-01.S/dut; riscv64-unknown-elf-gcc -march=rv64i          -static -mcmodel=medany -fvisibility=hidden -nostdlib -nostartfiles -g         -T /workspace/zisk/env/link.ld         -I /workspace/zisk/env/         -I /workspace/riscv-arch-test/riscv-test-suite/env /workspace/riscv-arch-test/riscv-test-suite/rv64i_m/I/src/sra-01.S -o my.elf  -DTEST_CASE_1=True -DXLEN=64 -Xlinker -Map=output.map -mabi=lp64 ; /program -e my.elf >/workspace/output/riscof_work/rv64i_m/I/src/sra-01.S/dut/DUT-zisk.signature;

.PHONY : TARGET57
TARGET57 :
	@cd /workspace/output/riscof_work/rv64i_m/I/src/srai-01.S/dut; riscv64-unknown-elf-gcc -march=rv64i          -static -mcmodel=medany -fvisibility=hidden -nostdlib -nostartfiles -g         -T /workspace/zisk/env/link.ld         -I /workspace/zisk/env/         -I /workspace/riscv-arch-test/riscv-test-suite/env /workspace/riscv-arch-test/riscv-test-suite/rv64i_m/I/src/srai-01.S -o my.elf  -DTEST_CASE_1=True -DXLEN=64 -Xlinker -Map=output.map -mabi=lp64 ; /program -e my.elf >/workspace/output/riscof_work/rv64i_m/I/src/srai-01.S/dut/DUT-zisk.signature;

.PHONY : TARGET58
TARGET58 :
	@cd /workspace/output/riscof_work/rv64i_m/I/src/sraiw-01.S/dut; riscv64-unknown-elf-gcc -march=rv64i          -static -mcmodel=medany -fvisibility=hidden -nostdlib -nostartfiles -g         -T /workspace/zisk/env/link.ld         -I /workspace/zisk/env/         -I /workspace/riscv-arch-test/riscv-test-suite/env /workspace/riscv-arch-test/riscv-test-suite/rv64i_m/I/src/sraiw-01.S -o my.elf  -DTEST_CASE_1=True -DXLEN=64 -Xlinker -Map=output.map -mabi=lp64 ; /program -e my.elf >/workspace/output/riscof_work/rv64i_m/I/src/sraiw-01.S/dut/DUT-zisk.signature;

.PHONY : TARGET59
TARGET59 :
	@cd /workspace/output/riscof_work/rv64i_m/I/src/sraw-01.S/dut; riscv64-unknown-elf-gcc -march=rv64i          -static -mcmodel=medany -fvisibility=hidden -nostdlib -nostartfiles -g         -T /workspace/zisk/env/link.ld         -I /workspace/zisk/env/         -I /workspace/riscv-arch-test/riscv-test-suite/env /workspace/riscv-arch-test/riscv-test-suite/rv64i_m/I/src/sraw-01.S -o my.elf  -DTEST_CASE_1=True -DXLEN=64 -Xlinker -Map=output.map -mabi=lp64 ; /program -e my.elf >/workspace/output/riscof_work/rv64i_m/I/src/sraw-01.S/dut/DUT-zisk.signature;

.PHONY : TARGET60
TARGET60 :
	@cd /workspace/output/riscof_work/rv64i_m/I/src/srl-01.S/dut; riscv64-unknown-elf-gcc -march=rv64i          -static -mcmodel=medany -fvisibility=hidden -nostdlib -nostartfiles -g         -T /workspace/zisk/env/link.ld         -I /workspace/zisk/env/         -I /workspace/riscv-arch-test/riscv-test-suite/env /workspace/riscv-arch-test/riscv-test-suite/rv64i_m/I/src/srl-01.S -o my.elf  -DTEST_CASE_1=True -DXLEN=64 -Xlinker -Map=output.map -mabi=lp64 ; /program -e my.elf >/workspace/output/riscof_work/rv64i_m/I/src/srl-01.S/dut/DUT-zisk.signature;

.PHONY : TARGET61
TARGET61 :
	@cd /workspace/output/riscof_work/rv64i_m/I/src/srli-01.S/dut; riscv64-unknown-elf-gcc -march=rv64i          -static -mcmodel=medany -fvisibility=hidden -nostdlib -nostartfiles -g         -T /workspace/zisk/env/link.ld         -I /workspace/zisk/env/         -I /workspace/riscv-arch-test/riscv-test-suite/env /workspace/riscv-arch-test/riscv-test-suite/rv64i_m/I/src/srli-01.S -o my.elf  -DTEST_CASE_1=True -DXLEN=64 -Xlinker -Map=output.map -mabi=lp64 ; /program -e my.elf >/workspace/output/riscof_work/rv64i_m/I/src/srli-01.S/dut/DUT-zisk.signature;

.PHONY : TARGET62
TARGET62 :
	@cd /workspace/output/riscof_work/rv64i_m/I/src/srliw-01.S/dut; riscv64-unknown-elf-gcc -march=rv64i          -static -mcmodel=medany -fvisibility=hidden -nostdlib -nostartfiles -g         -T /workspace/zisk/env/link.ld         -I /workspace/zisk/env/         -I /workspace/riscv-arch-test/riscv-test-suite/env /workspace/riscv-arch-test/riscv-test-suite/rv64i_m/I/src/srliw-01.S -o my.elf  -DTEST_CASE_1=True -DXLEN=64 -Xlinker -Map=output.map -mabi=lp64 ; /program -e my.elf >/workspace/output/riscof_work/rv64i_m/I/src/srliw-01.S/dut/DUT-zisk.signature;

.PHONY : TARGET63
TARGET63 :
	@cd /workspace/output/riscof_work/rv64i_m/I/src/srlw-01.S/dut; riscv64-unknown-elf-gcc -march=rv64i          -static -mcmodel=medany -fvisibility=hidden -nostdlib -nostartfiles -g         -T /workspace/zisk/env/link.ld         -I /workspace/zisk/env/         -I /workspace/riscv-arch-test/riscv-test-suite/env /workspace/riscv-arch-test/riscv-test-suite/rv64i_m/I/src/srlw-01.S -o my.elf  -DTEST_CASE_1=True -DXLEN=64 -Xlinker -Map=output.map -mabi=lp64 ; /program -e my.elf >/workspace/output/riscof_work/rv64i_m/I/src/srlw-01.S/dut/DUT-zisk.signature;

.PHONY : TARGET64
TARGET64 :
	@cd /workspace/output/riscof_work/rv64i_m/I/src/sub-01.S/dut; riscv64-unknown-elf-gcc -march=rv64i          -static -mcmodel=medany -fvisibility=hidden -nostdlib -nostartfiles -g         -T /workspace/zisk/env/link.ld         -I /workspace/zisk/env/         -I /workspace/riscv-arch-test/riscv-test-suite/env /workspace/riscv-arch-test/riscv-test-suite/rv64i_m/I/src/sub-01.S -o my.elf  -DTEST_CASE_1=True -DXLEN=64 -Xlinker -Map=output.map -mabi=lp64 ; /program -e my.elf >/workspace/output/riscof_work/rv64i_m/I/src/sub-01.S/dut/DUT-zisk.signature;

.PHONY : TARGET65
TARGET65 :
	@cd /workspace/output/riscof_work/rv64i_m/I/src/subw-01.S/dut; riscv64-unknown-elf-gcc -march=rv64i          -static -mcmodel=medany -fvisibility=hidden -nostdlib -nostartfiles -g         -T /workspace/zisk/env/link.ld         -I /workspace/zisk/env/         -I /workspace/riscv-arch-test/riscv-test-suite/env /workspace/riscv-arch-test/riscv-test-suite/rv64i_m/I/src/subw-01.S -o my.elf  -DTEST_CASE_1=True -DXLEN=64 -Xlinker -Map=output.map -mabi=lp64 ; /program -e my.elf >/workspace/output/riscof_work/rv64i_m/I/src/subw-01.S/dut/DUT-zisk.signature;

.PHONY : TARGET66
TARGET66 :
	@cd /workspace/output/riscof_work/rv64i_m/I/src/sw-align-01.S/dut; riscv64-unknown-elf-gcc -march=rv64i          -static -mcmodel=medany -fvisibility=hidden -nostdlib -nostartfiles -g         -T /workspace/zisk/env/link.ld         -I /workspace/zisk/env/         -I /workspace/riscv-arch-test/riscv-test-suite/env /workspace/riscv-arch-test/riscv-test-suite/rv64i_m/I/src/sw-align-01.S -o my.elf  -DTEST_CASE_1=True -DXLEN=64 -Xlinker -Map=output.map -mabi=lp64 ; /program -e my.elf >/workspace/output/riscof_work/rv64i_m/I/src/sw-align-01.S/dut/DUT-zisk.signature;

.PHONY : TARGET67
TARGET67 :
	@cd /workspace/output/riscof_work/rv64i_m/I/src/xor-01.S/dut; riscv64-unknown-elf-gcc -march=rv64i          -static -mcmodel=medany -fvisibility=hidden -nostdlib -nostartfiles -g         -T /workspace/zisk/env/link.ld         -I /workspace/zisk/env/         -I /workspace/riscv-arch-test/riscv-test-suite/env /workspace/riscv-arch-test/riscv-test-suite/rv64i_m/I/src/xor-01.S -o my.elf  -DTEST_CASE_1=True -DXLEN=64 -Xlinker -Map=output.map -mabi=lp64 ; /program -e my.elf >/workspace/output/riscof_work/rv64i_m/I/src/xor-01.S/dut/DUT-zisk.signature;

.PHONY : TARGET68
TARGET68 :
	@cd /workspace/output/riscof_work/rv64i_m/I/src/xori-01.S/dut; riscv64-unknown-elf-gcc -march=rv64i          -static -mcmodel=medany -fvisibility=hidden -nostdlib -nostartfiles -g         -T /workspace/zisk/env/link.ld         -I /workspace/zisk/env/         -I /workspace/riscv-arch-test/riscv-test-suite/env /workspace/riscv-arch-test/riscv-test-suite/rv64i_m/I/src/xori-01.S -o my.elf  -DTEST_CASE_1=True -DXLEN=64 -Xlinker -Map=output.map -mabi=lp64 ; /program -e my.elf >/workspace/output/riscof_work/rv64i_m/I/src/xori-01.S/dut/DUT-zisk.signature;

.PHONY : TARGET69
TARGET69 :
	@cd /workspace/output/riscof_work/rv64i_m/M/src/div-01.S/dut; riscv64-unknown-elf-gcc -march=rv64im          -static -mcmodel=medany -fvisibility=hidden -nostdlib -nostartfiles -g         -T /workspace/zisk/env/link.ld         -I /workspace/zisk/env/         -I /workspace/riscv-arch-test/riscv-test-suite/env /workspace/riscv-arch-test/riscv-test-suite/rv64i_m/M/src/div-01.S -o my.elf  -DTEST_CASE_1=True -DXLEN=64 -Xlinker -Map=output.map -mabi=lp64 ; /program -e my.elf >/workspace/output/riscof_work/rv64i_m/M/src/div-01.S/dut/DUT-zisk.signature;

.PHONY : TARGET70
TARGET70 :
	@cd /workspace/output/riscof_work/rv64i_m/M/src/divu-01.S/dut; riscv64-unknown-elf-gcc -march=rv64im          -static -mcmodel=medany -fvisibility=hidden -nostdlib -nostartfiles -g         -T /workspace/zisk/env/link.ld         -I /workspace/zisk/env/         -I /workspace/riscv-arch-test/riscv-test-suite/env /workspace/riscv-arch-test/riscv-test-suite/rv64i_m/M/src/divu-01.S -o my.elf  -DTEST_CASE_1=True -DXLEN=64 -Xlinker -Map=output.map -mabi=lp64 ; /program -e my.elf >/workspace/output/riscof_work/rv64i_m/M/src/divu-01.S/dut/DUT-zisk.signature;

.PHONY : TARGET71
TARGET71 :
	@cd /workspace/output/riscof_work/rv64i_m/M/src/divuw-01.S/dut; riscv64-unknown-elf-gcc -march=rv64im          -static -mcmodel=medany -fvisibility=hidden -nostdlib -nostartfiles -g         -T /workspace/zisk/env/link.ld         -I /workspace/zisk/env/         -I /workspace/riscv-arch-test/riscv-test-suite/env /workspace/riscv-arch-test/riscv-test-suite/rv64i_m/M/src/divuw-01.S -o my.elf  -DTEST_CASE_1=True -DXLEN=64 -Xlinker -Map=output.map -mabi=lp64 ; /program -e my.elf >/workspace/output/riscof_work/rv64i_m/M/src/divuw-01.S/dut/DUT-zisk.signature;

.PHONY : TARGET72
TARGET72 :
	@cd /workspace/output/riscof_work/rv64i_m/M/src/divw-01.S/dut; riscv64-unknown-elf-gcc -march=rv64im          -static -mcmodel=medany -fvisibility=hidden -nostdlib -nostartfiles -g         -T /workspace/zisk/env/link.ld         -I /workspace/zisk/env/         -I /workspace/riscv-arch-test/riscv-test-suite/env /workspace/riscv-arch-test/riscv-test-suite/rv64i_m/M/src/divw-01.S -o my.elf  -DTEST_CASE_1=True -DXLEN=64 -Xlinker -Map=output.map -mabi=lp64 ; /program -e my.elf >/workspace/output/riscof_work/rv64i_m/M/src/divw-01.S/dut/DUT-zisk.signature;

.PHONY : TARGET73
TARGET73 :
	@cd /workspace/output/riscof_work/rv64i_m/M/src/mul-01.S/dut; riscv64-unknown-elf-gcc -march=rv64im          -static -mcmodel=medany -fvisibility=hidden -nostdlib -nostartfiles -g         -T /workspace/zisk/env/link.ld         -I /workspace/zisk/env/         -I /workspace/riscv-arch-test/riscv-test-suite/env /workspace/riscv-arch-test/riscv-test-suite/rv64i_m/M/src/mul-01.S -o my.elf  -DTEST_CASE_1=True -DXLEN=64 -Xlinker -Map=output.map -mabi=lp64 ; /program -e my.elf >/workspace/output/riscof_work/rv64i_m/M/src/mul-01.S/dut/DUT-zisk.signature;

.PHONY : TARGET74
TARGET74 :
	@cd /workspace/output/riscof_work/rv64i_m/M/src/mulh-01.S/dut; riscv64-unknown-elf-gcc -march=rv64im          -static -mcmodel=medany -fvisibility=hidden -nostdlib -nostartfiles -g         -T /workspace/zisk/env/link.ld         -I /workspace/zisk/env/         -I /workspace/riscv-arch-test/riscv-test-suite/env /workspace/riscv-arch-test/riscv-test-suite/rv64i_m/M/src/mulh-01.S -o my.elf  -DTEST_CASE_1=True -DXLEN=64 -Xlinker -Map=output.map -mabi=lp64 ; /program -e my.elf >/workspace/output/riscof_work/rv64i_m/M/src/mulh-01.S/dut/DUT-zisk.signature;

.PHONY : TARGET75
TARGET75 :
	@cd /workspace/output/riscof_work/rv64i_m/M/src/mulhsu-01.S/dut; riscv64-unknown-elf-gcc -march=rv64im          -static -mcmodel=medany -fvisibility=hidden -nostdlib -nostartfiles -g         -T /workspace/zisk/env/link.ld         -I /workspace/zisk/env/         -I /workspace/riscv-arch-test/riscv-test-suite/env /workspace/riscv-arch-test/riscv-test-suite/rv64i_m/M/src/mulhsu-01.S -o my.elf  -DTEST_CASE_1=True -DXLEN=64 -Xlinker -Map=output.map -mabi=lp64 ; /program -e my.elf >/workspace/output/riscof_work/rv64i_m/M/src/mulhsu-01.S/dut/DUT-zisk.signature;

.PHONY : TARGET76
TARGET76 :
	@cd /workspace/output/riscof_work/rv64i_m/M/src/mulhu-01.S/dut; riscv64-unknown-elf-gcc -march=rv64im          -static -mcmodel=medany -fvisibility=hidden -nostdlib -nostartfiles -g         -T /workspace/zisk/env/link.ld         -I /workspace/zisk/env/         -I /workspace/riscv-arch-test/riscv-test-suite/env /workspace/riscv-arch-test/riscv-test-suite/rv64i_m/M/src/mulhu-01.S -o my.elf  -DTEST_CASE_1=True -DXLEN=64 -Xlinker -Map=output.map -mabi=lp64 ; /program -e my.elf >/workspace/output/riscof_work/rv64i_m/M/src/mulhu-01.S/dut/DUT-zisk.signature;

.PHONY : TARGET77
TARGET77 :
	@cd /workspace/output/riscof_work/rv64i_m/M/src/mulw-01.S/dut; riscv64-unknown-elf-gcc -march=rv64im          -static -mcmodel=medany -fvisibility=hidden -nostdlib -nostartfiles -g         -T /workspace/zisk/env/link.ld         -I /workspace/zisk/env/         -I /workspace/riscv-arch-test/riscv-test-suite/env /workspace/riscv-arch-test/riscv-test-suite/rv64i_m/M/src/mulw-01.S -o my.elf  -DTEST_CASE_1=True -DXLEN=64 -Xlinker -Map=output.map -mabi=lp64 ; /program -e my.elf >/workspace/output/riscof_work/rv64i_m/M/src/mulw-01.S/dut/DUT-zisk.signature;

.PHONY : TARGET78
TARGET78 :
	@cd /workspace/output/riscof_work/rv64i_m/M/src/rem-01.S/dut; riscv64-unknown-elf-gcc -march=rv64im          -static -mcmodel=medany -fvisibility=hidden -nostdlib -nostartfiles -g         -T /workspace/zisk/env/link.ld         -I /workspace/zisk/env/         -I /workspace/riscv-arch-test/riscv-test-suite/env /workspace/riscv-arch-test/riscv-test-suite/rv64i_m/M/src/rem-01.S -o my.elf  -DTEST_CASE_1=True -DXLEN=64 -Xlinker -Map=output.map -mabi=lp64 ; /program -e my.elf >/workspace/output/riscof_work/rv64i_m/M/src/rem-01.S/dut/DUT-zisk.signature;

.PHONY : TARGET79
TARGET79 :
	@cd /workspace/output/riscof_work/rv64i_m/M/src/remu-01.S/dut; riscv64-unknown-elf-gcc -march=rv64im          -static -mcmodel=medany -fvisibility=hidden -nostdlib -nostartfiles -g         -T /workspace/zisk/env/link.ld         -I /workspace/zisk/env/         -I /workspace/riscv-arch-test/riscv-test-suite/env /workspace/riscv-arch-test/riscv-test-suite/rv64i_m/M/src/remu-01.S -o my.elf  -DTEST_CASE_1=True -DXLEN=64 -Xlinker -Map=output.map -mabi=lp64 ; /program -e my.elf >/workspace/output/riscof_work/rv64i_m/M/src/remu-01.S/dut/DUT-zisk.signature;

.PHONY : TARGET80
TARGET80 :
	@cd /workspace/output/riscof_work/rv64i_m/M/src/remuw-01.S/dut; riscv64-unknown-elf-gcc -march=rv64im          -static -mcmodel=medany -fvisibility=hidden -nostdlib -nostartfiles -g         -T /workspace/zisk/env/link.ld         -I /workspace/zisk/env/         -I /workspace/riscv-arch-test/riscv-test-suite/env /workspace/riscv-arch-test/riscv-test-suite/rv64i_m/M/src/remuw-01.S -o my.elf  -DTEST_CASE_1=True -DXLEN=64 -Xlinker -Map=output.map -mabi=lp64 ; /program -e my.elf >/workspace/output/riscof_work/rv64i_m/M/src/remuw-01.S/dut/DUT-zisk.signature;

.PHONY : TARGET81
TARGET81 :
	@cd /workspace/output/riscof_work/rv64i_m/M/src/remw-01.S/dut; riscv64-unknown-elf-gcc -march=rv64im          -static -mcmodel=medany -fvisibility=hidden -nostdlib -nostartfiles -g         -T /workspace/zisk/env/link.ld         -I /workspace/zisk/env/         -I /workspace/riscv-arch-test/riscv-test-suite/env /workspace/riscv-arch-test/riscv-test-suite/rv64i_m/M/src/remw-01.S -o my.elf  -DTEST_CASE_1=True -DXLEN=64 -Xlinker -Map=output.map -mabi=lp64 ; /program -e my.elf >/workspace/output/riscof_work/rv64i_m/M/src/remw-01.S/dut/DUT-zisk.signature;