mod arith_eq;
// mod bigint;
// mod keccakf;
// mod sha256f;
mod arith_eq_384;
mod builder;

pub use arith_eq::generate_arith_eq_tests;
// pub use bigint::generate_bigint_tests;
// pub use keccakf::generate_keccakf_tests;
// pub use sha256f::generate_sha256f_tests;
pub use arith_eq_384::generate_arith_eq_384_tests;
pub use builder::ProgramBuilder;

use std::fs::File;
use std::io::{BufWriter, Write};
use std::path::Path;

pub fn generate_main_file(output_path: &Path, modules: &[(String, String)]) {
    let main_file = output_path.join("main.rs");
    let file = File::create(&main_file).expect("Failed to create main.rs");
    let mut writer = BufWriter::new(file);

    // Write header
    writeln!(writer, "//! Generated main test file.").unwrap();
    writeln!(writer, "//! DO NOT EDIT - This file is automatically generated.").unwrap();
    writeln!(writer).unwrap();

    writeln!(writer, "#![no_main]").unwrap();
    writeln!(writer, "#![cfg(all(target_os = \"zkvm\", target_vendor = \"zisk\"))]").unwrap();
    writeln!(writer, "ziskos::entrypoint!(main);").unwrap();
    writeln!(writer).unwrap();

    // Import modules
    for (module_name, _) in modules {
        writeln!(writer, "mod {};", module_name).unwrap();
    }
    writeln!(writer).unwrap();

    // Write main function
    writeln!(writer, "fn main() {{").unwrap();
    for (module_name, function_name) in modules {
        writeln!(writer, "\t{}::{}();", module_name, function_name).unwrap();
    }
    writeln!(writer, "}}").unwrap();

    writer.flush().expect("Failed to flush main.rs");
    println!("Generated main file: {:?}", main_file);
}
